osx_image: xcode10.1
language: swift
before_install:
- cd Redux-ReactiveSwift
- bundle install
- pod repo update
script:
- fastlane ios cocoapods_test
- fastlane ios carthage_test
- cd ..
- bundle exec pod lib lint --verbose
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Redux-ReactiveSwift'
